<a href="https://colab.research.google.com/github/nirbhay221/MovieRecommenation/blob/master/Movie_Recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np 
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
df = pd.read_csv('movies.csv')
df.head(3)

Id                                Film  ... Worldwide Gross  Year
0   0          Zack and Miri Make a Porno  ...         $41.94   2008
1   1                     Youth in Revolt  ...         $19.62   2010
2   2  You Will Meet a Tall Dark Stranger  ...         $26.66   2010

[3 rows x 9 columns]

In [ ]:
df.shape[0]


77

In [ ]:
columns = ['Film','Genre','Lead Studio']


In [ ]:
df[columns].head(3)

Film    Genre            Lead Studio
0          Zack and Miri Make a Porno  Romance  The Weinstein Company
1                     Youth in Revolt   Comedy  The Weinstein Company
2  You Will Meet a Tall Dark Stranger   Comedy            Independent

In [ ]:
df[columns].isnull().values.any()

False

In [ ]:
def get_important_features(data):
  important_features = []
  for i in range(0,data.shape[0]):  
    important_features.append(data['Film'][i]+''+data['Genre'][i]+''+data['Lead Studio'][i]+'')
    return important_features

In [ ]:
df['important_features'] = df.apply(lambda row: row.Film + '' + row.Genre +''+'' , axis = 1) 
  
df.head(3)

Id  ...                        important_features
0   0  ...         Zack and Miri Make a PornoRomance
1   1  ...                     Youth in RevoltComedy
2   2  ...  You Will Meet a Tall Dark StrangerComedy

[3 rows x 10 columns]

In [ ]:
cm = CountVectorizer().fit_transform(df['important_features'])

In [ ]:
cs = cosine_similarity(cm)

In [ ]:
print(cs)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [ ]:
cs.shape

(77, 77)

In [ ]:
df.head(77)

Id  ...                        important_features
0    0  ...         Zack and Miri Make a PornoRomance
1    1  ...                     Youth in RevoltComedy
2    2  ...  You Will Meet a Tall Dark StrangerComedy
3    3  ...                        When in RomeComedy
4    4  ...               What Happens in VegasComedy
..  ..  ...                                       ...
72  72  ...                Across the Universeromance
73  73  ...                        A Serious ManDrama
74  74  ...                   A Dangerous MethodDrama
75  75  ...                          27 DressesComedy
76  76  ...                (500) Days of Summercomedy

[77 rows x 10 columns]

In [ ]:
DF.HEAD(10)

NameError: ignored

In [ ]:
df.head(10)

Id  ...                        important_features
0   0  ...         Zack and Miri Make a PornoRomance
1   1  ...                     Youth in RevoltComedy
2   2  ...  You Will Meet a Tall Dark StrangerComedy
3   3  ...                        When in RomeComedy
4   4  ...               What Happens in VegasComedy
5   5  ...                  Water For ElephantsDrama
6   6  ...                           WALL-EAnimation
7   7  ...                           WaitressRomance
8   8  ...                Waiting For ForeverRomance
9   9  ...                     Valentine's DayComedy

[10 rows x 10 columns]

In [ ]:
Film = 'When in Rome'
movie_id = df[df.Film == Film]['Id'].values[0]

In [ ]:
scores = list(enumerate(cs[movie_id]))

In [ ]:
sorted_scores = sorted(scores,key = lambda x:x[1],reverse = True)
sorted_scores= sorted_scores[1:]
print(sorted_scores)

[(1, 0.3333333333333334), (43, 0.3333333333333334), (4, 0.2886751345948129), (0, 0.0), (2, 0.0), (5, 0.0), (6, 0.0), (7, 0.0), (8, 0.0), (9, 0.0), (10, 0.0), (11, 0.0), (12, 0.0), (13, 0.0), (14, 0.0), (15, 0.0), (16, 0.0), (17, 0.0), (18, 0.0), (19, 0.0), (20, 0.0), (21, 0.0), (22, 0.0), (23, 0.0), (24, 0.0), (25, 0.0), (26, 0.0), (27, 0.0), (28, 0.0), (29, 0.0), (30, 0.0), (31, 0.0), (32, 0.0), (33, 0.0), (34, 0.0), (35, 0.0), (36, 0.0), (37, 0.0), (38, 0.0), (39, 0.0), (40, 0.0), (41, 0.0), (42, 0.0), (44, 0.0), (45, 0.0), (46, 0.0), (47, 0.0), (48, 0.0), (49, 0.0), (50, 0.0), (51, 0.0), (52, 0.0), (53, 0.0), (54, 0.0), (55, 0.0), (56, 0.0), (57, 0.0), (58, 0.0), (59, 0.0), (60, 0.0), (61, 0.0), (62, 0.0), (63, 0.0), (64, 0.0), (65, 0.0), (66, 0.0), (67, 0.0), (68, 0.0), (69, 0.0), (70, 0.0), (71, 0.0), (72, 0.0), (73, 0.0), (74, 0.0), (75, 0.0), (76, 0.0)]


In [ ]:
j = 0 
print('the 7 most similar recommended movies to ' ,Film ,'are: \n')
for item in sorted_scores:
  Film = df[df.Id == item[0]]['Film'].values[0]
  print(j+1,Film)
  j = j+1
  if j>6 :
    break 

the 7 most similar recommended movies to  When in Rome are: 

1 Youth in Revolt
2 Midnight in Paris
3 What Happens in Vegas
4 Zack and Miri Make a Porno
5 You Will Meet a Tall Dark Stranger
6 Water For Elephants
7 WALL-E
